from ib_users.validators.base_validator import CustomException


class InvalidLoginTypeException(CustomException):
    pass
